name: Terraform

on:
  pull_request:
    paths:
      - 'network/**'
  push:
    branches:
      - main
    paths:
      - 'network/**'

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.7'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        working-directory: ./network
        run: terraform init -input=false

      - name: Terraform Format Check
        working-directory: ./network
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ./network
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        working-directory: ./network
        run: terraform plan -input=false

      - name: Terraform Plan (main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: ./network
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply (auto-approve)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: ./network
        run: terraform apply -input=false -auto-approve tfplan
